version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/paradise-donut-app

permissions:
  - object: scripts
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
